# CLEANING

In [238]:
import pandas as pd

## Event cleaning

In [239]:
df = pd.read_csv("../data/raw/events.csv")

In [240]:
df.shape

(2756101, 5)

In [241]:
df.head()

       timestamp  visitorid event  itemid  transactionid
0  1433221332117     257597  view  355908            NaN
1  1433224214164     992329  view  248676            NaN
2  1433221999827     111016  view  318965            NaN
3  1433221955914     483717  view  253185            NaN
4  1433221337106     951259  view  367447            NaN

In [242]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2756101 entries, 0 to 2756100
Data columns (total 5 columns):
 #   Column         Dtype
---  ------         -----
 0   timestamp      int64
 1   visitorid      int64
 2   event          str
 3   itemid         int64
 4   transactionid  float64
dtypes: float64(1), int64(3), str(1)
memory usage: 105.1 MB

In [243]:
df.isna().sum()

timestamp              0
visitorid              0
event                  0
itemid                 0
transactionid    2733644
dtype: int64

In [244]:
df.nunique()

timestamp        2750455
visitorid        1407580
event                  3
itemid            235061
transactionid      17672
dtype: int64

In [245]:
df['event'].value_counts()

event
view           2664312
addtocart        69332
transaction      22457
Name: count, dtype: int64

In [246]:
df['datetime'] = pd.to_datetime(df['timestamp'], unit = 'ms')

In [247]:
df.head()

,timestamp,visitorid,event,itemid,transactionid,datetime
0,1433221332117,257597,view,355908,NaN,2015-06-02 05:02:12.117
1,1433224214164,992329,view,248676,NaN,2015-06-02 05:50:14.164
2,1433221999827,111016,view,318965,NaN,2015-06-02 05:13:19.827
3,1433221955914,483717,view,253185,NaN,2015-06-02 05:12:35.914
4,1433221337106,951259,view,367447,NaN,2015-06-02 05:02:17.106

In [248]:
df['datetime'].max()

Timestamp('2015-09-18 02:59:47.788000')

In [249]:
df['datetime'].min()

Timestamp('2015-05-03 03:00:04.384000')

### Сколько событий в среднем приходится на одного пользователя?

In [250]:
len(df)/df['visitorid'].nunique()

1.9580421716705267

### Количество событий для каждого visitorid

In [251]:
df['visitorid'].value_counts()

visitorid
1150086    7757
530559     4328
152963     3024
895999     2474
163561     2410
           ...
1392454       1
226214        1
591435        1
762376        1
1184451       1
Name: count, Length: 1407580, dtype: int64

In [252]:
events_per_user = df['visitorid'].value_counts()

In [253]:
events_per_user.describe()

count    1.407580e+06
mean     1.958042e+00
std      1.258049e+01
min      1.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      2.000000e+00
max      7.757000e+03
Name: count, dtype: float64

### Проверка дубликатов

In [254]:
df.duplicated().sum()

np.int64(460)

In [255]:
df[df.duplicated(keep=False)]

,timestamp,visitorid,event,itemid,transactionid,datetime
13734,1433180781440,1045411,addtocart,379647,NaN,2015-06-01 17:46:21.440
22404,1433180781440,1045411,addtocart,379647,NaN,2015-06-01 17:46:21.440
24476,1433274223925,366538,addtocart,252068,NaN,2015-06-02 19:43:43.925
25508,1433265100661,198153,addtocart,48715,NaN,2015-06-02 17:11:40.661
27095,1433270868154,1268755,view,60980,NaN,2015-06-02 18:47:48.154
...,...,...,...,...,...,...
2748964,1438346018813,722488,view,97303,NaN,2015-07-31 12:33:38.813
2750464,1438370523152,896869,addtocart,85004,NaN,2015-07-31 19:22:03.152
2752725,1438405570135,708442,addtocart,392883,NaN,2015-08-01 05:06:10.135
2753763,1438376127329,372829,addtocart,388276,NaN,2015-07-31 20:55:27.329
2755356,1438378507708,415611,addtocart,177728,NaN,2015-07-31 21:35:07.708

In [256]:
df = df.drop_duplicates()

In [257]:
df.duplicated().sum()

np.int64(0)

In [258]:
df.shape

(2755641, 6)

### Проверка пропусков

In [259]:
df.isna().sum()

timestamp              0
visitorid              0
event                  0
itemid                 0
transactionid    2733184
datetime               0
dtype: int64

In [260]:
df.groupby('event')['transactionid'].apply(lambda x: x.isna().sum())

event
addtocart        68966
transaction          0
view           2664218
Name: transactionid, dtype: int64

### Проверка типов данных после очистки

In [261]:
df.dtypes

timestamp                 int64
visitorid                 int64
event                       str
itemid                    int64
transactionid           float64
datetime         datetime64[ms]
dtype: object

### Преобразование типов после очистки

In [262]:
df['transactionid'] = df['transactionid'].astype('Int64')

In [263]:
df.dtypes

timestamp                 int64
visitorid                 int64
event                       str
itemid                    int64
transactionid             Int64
datetime         datetime64[ms]
dtype: object

In [264]:
df.head()

,timestamp,visitorid,event,itemid,transactionid,datetime
0,1433221332117,257597,view,355908,<NA>,2015-06-02 05:02:12.117
1,1433224214164,992329,view,248676,<NA>,2015-06-02 05:50:14.164
2,1433221999827,111016,view,318965,<NA>,2015-06-02 05:13:19.827
3,1433221955914,483717,view,253185,<NA>,2015-06-02 05:12:35.914
4,1433221337106,951259,view,367447,<NA>,2015-06-02 05:02:17.106

In [265]:
df = df.drop(columns=['timestamp'])

In [266]:
df.head()

   visitorid event  itemid  transactionid                datetime
0     257597  view  355908           <NA> 2015-06-02 05:02:12.117
1     992329  view  248676           <NA> 2015-06-02 05:50:14.164
2     111016  view  318965           <NA> 2015-06-02 05:13:19.827
3     483717  view  253185           <NA> 2015-06-02 05:12:35.914
4     951259  view  367447           <NA> 2015-06-02 05:02:17.106

In [267]:
df.dtypes

visitorid                 int64
event                       str
itemid                    int64
transactionid             Int64
datetime         datetime64[ms]
dtype: object

### Проверка допустимых значений

In [268]:
df['event'].value_counts()

event
view           2664218
addtocart        68966
transaction      22457
Name: count, dtype: int64

In [269]:
df[df['visitorid'] < 0]

Empty DataFrame
Columns: [visitorid, event, itemid, transactionid, datetime]
Index: []

In [270]:
df[df['itemid'] < 0]

Empty DataFrame
Columns: [visitorid, event, itemid, transactionid, datetime]
Index: []

In [271]:
df[df['transactionid'] < 0]

Empty DataFrame
Columns: [visitorid, event, itemid, transactionid, datetime]
Index: []

In [272]:
df.to_csv(
    '../data/processed/events_clean.csv',
    index=False
)

## Item properties cleaning

In [273]:
item_part1 = pd.read_csv('../data/raw/item_properties_part1.csv')

In [274]:
item_part2 = pd.read_csv('../data/raw/item_properties_part2.csv')

In [275]:
print(item_part1.head())
print(item_part1.shape)
print(item_part1.dtypes)

       timestamp  itemid    property                            value
0  1435460400000  460429  categoryid                             1338
1  1441508400000  206783         888          1116713 960601 n277.200
2  1439089200000  395014         400  n552.000 639502 n720.000 424566
3  1431226800000   59481         790                       n15360.000
4  1431831600000  156781         917                           828513
(10999999, 4)
timestamp    int64
itemid       int64
property       str
value          str
dtype: object

In [276]:
print(item_part2.head())
print(item_part2.shape)
print(item_part2.dtypes)

       timestamp  itemid property            value
0  1433041200000  183478      561           769062
1  1439694000000  132256      976  n26.400 1135780
2  1435460400000  420307      921  1149317 1257525
3  1431831600000  403324      917          1204143
4  1435460400000  230701      521           769062
(9275903, 4)
timestamp    int64
itemid       int64
property       str
value          str
dtype: object

In [277]:
items = pd.concat([item_part1, item_part2], ignore_index=True)

In [278]:
print(items.head())
print(items.shape)
print(items.dtypes)

       timestamp  itemid    property                            value
0  1435460400000  460429  categoryid                             1338
1  1441508400000  206783         888          1116713 960601 n277.200
2  1439089200000  395014         400  n552.000 639502 n720.000 424566
3  1431226800000   59481         790                       n15360.000
4  1431831600000  156781         917                           828513
(20275902, 4)
timestamp    int64
itemid       int64
property       str
value          str
dtype: object

### Проверка пропусков

In [279]:
items.isna().sum()

timestamp    0
itemid       0
property     0
value        0
dtype: int64

### Проверка дубликатов

In [280]:
items.duplicated().sum()

np.int64(0)

### Обработка времени

In [281]:
items['datetime_item'] = pd.to_datetime(items['timestamp'],unit='ms')

In [282]:
items.head()

,timestamp,itemid,property,value,datetime_item
0,1435460400000,460429,categoryid,1338,2015-06-28 03:00:00
1,1441508400000,206783,888,1116713 960601 n277.200,2015-09-06 03:00:00
2,1439089200000,395014,400,n552.000 639502 n720.000 424566,2015-08-09 03:00:00
3,1431226800000,59481,790,n15360.000,2015-05-10 03:00:00
4,1431831600000,156781,917,828513,2015-05-17 03:00:00

In [283]:
items.dtypes

timestamp                 int64
itemid                    int64
property                    str
value                       str
datetime_item    datetime64[ms]
dtype: object

In [284]:
print(items['datetime_item'].min())
print(items['datetime_item'].max())

2015-05-10 03:00:00
2015-09-13 03:00:00

In [285]:
items = items.drop(columns=['timestamp'])

In [286]:
items.head()

   itemid    property                            value       datetime_item
0  460429  categoryid                             1338 2015-06-28 03:00:00
1  206783         888          1116713 960601 n277.200 2015-09-06 03:00:00
2  395014         400  n552.000 639502 n720.000 424566 2015-08-09 03:00:00
3   59481         790                       n15360.000 2015-05-10 03:00:00
4  156781         917                           828513 2015-05-17 03:00:00

### Сколько вообще существует различных свойств товара?

In [287]:
items['property'].nunique()

1104

In [288]:
(items['property'] == 'categoryid').sum()

np.int64(788214)

### Для скольких уникальных товаров вообще присутствует categoryid?

In [289]:
items[items['property'] == 'categoryid']['itemid'].nunique()

417053

In [290]:
items['itemid'].nunique()

417053

In [291]:
print(f'coverege = {items[items['property'] == 'categoryid']['itemid'].nunique()/items['itemid'].nunique() * 100}')

coverege = 100.0

### Сколько товаров за весь период имели больше одного уникального categoryid?

In [292]:
items_cat = items[items['property'] == 'categoryid']

In [293]:
(items_cat.groupby('itemid')['value'].nunique() > 1).sum()

np.int64(23352)

In [294]:
category_count = items_cat.groupby('itemid')['value'].nunique()

In [295]:
category_count[category_count > 1].head()

itemid
25     2
94     2
130    2
149    2
168    2
Name: value, dtype: int64

In [296]:
items_cat[items_cat['itemid'] == 25].sort_values('datetime_item')

          itemid    property value       datetime_item
7786530       25  categoryid  1509 2015-05-10 03:00:00
8382882       25  categoryid  1509 2015-05-17 03:00:00
8581666       25  categoryid  1509 2015-05-24 03:00:00
8979234       25  categoryid  1509 2015-05-31 03:00:00
7985314       25  categoryid  1509 2015-06-07 03:00:00
8184098       25  categoryid  1509 2015-06-14 03:00:00
8780450       25  categoryid  1509 2015-06-28 03:00:00
9575586       25  categoryid  1509 2015-07-05 03:00:00
9376802       25  categoryid  1509 2015-07-12 03:00:00
9178018       25  categoryid  1509 2015-07-19 03:00:00
9774370       25  categoryid  1509 2015-07-26 03:00:00
10768290      25  categoryid  1509 2015-08-02 03:00:00
9973154       25  categoryid  1509 2015-08-09 03:00:00
10370722      25  categoryid    72 2015-08-16 03:00:00
10967074      25  categoryid    72 2015-08-23 03:00:00
10569506      25  categoryid    72 2015-08-30 03:00:00
11165857      25  categoryid    72 2015-09-06 03:00:00
10171938      25  categoryid    72 2015-09-13 03:00:00

In [297]:
items.to_csv('../data/processed/items_properties_clean.csv', index=False)

## Category tree cleaning

In [298]:
category_tree = pd.read_csv('../data/raw/category_tree.csv')

In [299]:
category_tree.head()

   categoryid  parentid
0        1016     213.0
1         809     169.0
2         570       9.0
3        1691     885.0
4         536    1691.0

In [300]:
category_tree.shape

(1669, 2)

In [301]:
category_tree.dtypes

categoryid      int64
parentid      float64
dtype: object

### Проверка на пропуски

In [302]:
category_tree.isna().sum()

categoryid     0
parentid      25
dtype: int64

### Проверка на дубликаты

In [303]:
category_tree.duplicated().sum()

np.int64(0)

### Корневые категории

In [304]:
category_tree[category_tree['parentid'].isna()]['categoryid'].nunique()

25

### Приведение типов

In [305]:
category_tree['parentid'] = category_tree['parentid'].astype('Int64')

In [306]:
category_tree.dtypes

categoryid    int64
parentid      Int64
dtype: object

### Проверка качества данных

In [307]:
category_tree_withoutna = category_tree[category_tree['parentid'].notna()]

In [308]:
(~category_tree_withoutna['parentid'].isin(category_tree['categoryid'])).sum()

np.int64(0)

In [309]:
category_tree.to_csv('../data/processed/category_tree_clean.csv', index=False)